# 기본 URL
baseURL = 'https://blog.plzhans.com'
# 제목
title = '부탁해스마일'
# 언어 코드
languageCode = 'ko-kr'

# 사용할 Hugo 테마
theme = "m10c"

# 기본 콘텐츠 언어
defaultContentLanguage = "ko"
# 기본 언어도 서브디렉토리에 포함 (/ko/)
defaultContentLanguageInSubdir = true

# robots.txt 파일 자동 생성
enableRobotsTXT = true
# 콘텐츠 디렉토리 경로 (기본값: content)
#contentDir = "contents"

# 다국어 설정
[languages]
  [languages.ko]
    weight = 1
    languageName = "한국어"

  [languages.en]
    weight = 2
    languageName = "English"

  [languages.ja]
    weight = 3
    languageName = "日本語"

# 사이트 파라미터 설정
[params]
  # 작성자 이름
  author = "plzhans"
  # 사이트 설명
  description = "개발자 블로그"
  # 프로필 이미지 경로
  avatar = "/avatar-plzhans.png"
  # 저작권 표시 HTML
  CopyrightHTML = 'Copyright &#xA9; plzhans. All Rights Reserved. | Powered by <a href="https://github.com/plzhans/hans-blog" target="_blank">github.com/plzhans/hans-blog</a>'
  # 메뉴 아이템 구분자
  menu_item_separator = " - "
  [[params.social]]
    icon = "brand-github"
    name = "Github"
    url = "https://github.com/plzhans"
  [[params.social]]
    icon = "code"
    name = "Source"
    url = "https://github.com/plzhans/hans-blog"
  [[params.social]]
    icon = "mail"
    name = "Email"
    url = "mailto:plzhans@gmail.com"
  [[params.social]]
    icon = "rss"
    name = "RSS"
    url = "/index.xml"

  [params.style]
    darkestColor = "#242930"
    darkColor = "#353b43"
    lightColor = "#afbac4"
    lightestColor = "#ffffff"
    primaryColor = "#57cc8a"

[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = false
    style = "monokai"
    lineNos = true
    lineNumbersInTable = false

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
#   [[menu.main]]
#     identifier = "about"
#     name = "About"
#     url = "/about/"
#     weight = 3

[taxonomies]
  category = "categories"
  tag = "tags"

[params.giscus]
  repo = "plzhans/hans-blog"
  repoId = "R_kgDORDHy7g"
  category = "General"
  categoryId = "DIC_kwDORDHy7s4C1zoX"
  mapping = "pathname"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "top"
  theme = "dark"
  lang = "ko"

[services]
  [services.googleAnalytics]
    ID = "G-7QCWSVX3WN"

